# Generated by Django 5.0.2 on 2026-07-17 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_text', models.TextField()),
                ('language', models.CharField(default='en', max_length=50)),
                ('accent', models.CharField(default='com', max_length=50)),
                ('speed', models.CharField(default='normal', max_length=10)),
                ('audio_file', models.FileField(upload_to='audio_conversions/')),
                ('word_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
