# Generated by Django 5.0.2 on 2026-07-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioconversion',
            name='accent',
        ),
        migrations.AddField(
            model_name='audioconversion',
            name='voice',
            field=models.CharField(default='en-US-AriaNeural', max_length=100),
        ),
    ]
