# Generated by Django 5.0.2 on 2026-07-21 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_remove_audioconversion_accent_audioconversion_voice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audioconversion',
            name='source_language',
            field=models.CharField(default='auto', max_length=50),
        ),
        migrations.AddField(
            model_name='audioconversion',
            name='translated_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audioconversion',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='audioconversion',
            name='video_style',
            field=models.CharField(blank=True, choices=[('waveform', 'Waveform Only'), ('captioned', 'Captioned Only'), ('both', 'Both Waveform & Captions')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='audioconversion',
            name='was_translated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('style', models.CharField(default='realistic', max_length=50)),
                ('image_file', models.ImageField(upload_to='generated_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
